source 'git@github.com:wanyakun/Specs.git'
source 'https://cdn.cocoapods.org/'

platform :ios, "10.0"
use_frameworks!

target 'YKRouter_Example' do
  pod 'YKRouter', :path => '../'
  pod 'SnapKit', '~> 5.6.0'

  target 'YKRouter_Tests' do
    inherit! :search_paths

    
  end
end
